_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.18
            "5": 0.18.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
alpha:
    value: 0.5
beta:
    value: 50
temperature:
    value: 20
